name: Script Testing

on:
  push:
     branches:
       - main
       - master
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: codecheckout
          uses: actions/checkout@v4
        - name: python setup
          uses: action/setup-python@v4
        - name: Install Poetry
          run: |
            curl -sSL https://install.python-poetry.org | python3 -
            echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
        - name: Install dependencies
          run: |
            poetry install
        - name: unitest
          run: |
            pytest
        - name: bash
          run: |
            echo "tested code successfully"
               
