name: Script Testing

on:
  push:
     branches:
       - main
       - master
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: codecheckout
          uses: actions/checkout@v4

        - name: unitest
          run: |
            pytest
        - name: bash
          run: |
            echo "tested code successfully"
               
