name: Script Testing

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Adjust Python version as needed

    # Step 3: Cache Poetry dependencies
    - name: Cache Poetry dependencies
      uses: actions/cache@v3
      with:
        path: |
          .venv
          $HOME/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    # Step 4: Install Poetry
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

    # Step 5: Change Directory
    - name: Change to project directory
      working-directory: ./aganaithtask
      run: echo "Changed to aganaithtask directory"

    # Step 6: Update lock file
    - name: Update lock file
      working-directory: ./aganaithtask
      run: poetry lock

    # Step 7: Install Dependencies
    - name: Install dependencies
      working-directory: ./aganaithtask
      run: poetry install

    # Step 8: Run Unit Tests
    - name: Run unit tests
      working-directory: ./aganaithtask
      run: poetry run pytest

    # Step 9: Output Success Message
    - name: Success message
      run: echo "Tested code successfully"
